# Generated by Django 5.0.7 on 2024-08-17 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_auction_bids_comments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
