# Generated by Django 5.0.7 on 2024-08-17 09:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0004_auction_created_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "NONE"),
                    ("ELEC", "Electronics"),
                    ("CLTH", "Clothing"),
                    ("TOYS", "Toys"),
                    ("FOOD", "Food and Beverage"),
                    ("FURN", "Furniture and Decor"),
                    ("MEDI", "Medicine"),
                    ("OFIC", "office equipment"),
                    ("OTHR", "Others"),
                ],
                default="",
                max_length=4,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="auction",
            name="photo",
            field=models.TextField(
                blank=True, default=None, max_length=2048, null=True
            ),
        ),
        migrations.AlterField(
            model_name="auction",
            name="watchers",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                null=True,
                related_name="watching",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
