# Generated by Django 5.0.7 on 2024-08-17 18:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0005_alter_auction_category_alter_auction_photo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="comments",
            name="created_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
